import { BRAND_NAME } from "@/lib/constants";

export const metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="font-display text-3xl font-extrabold text-charcoal-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-charcoal-400">
        Placeholder legal text for demo purposes. This page is structured for straightforward attorney review before production use — it is not a substitute for legal
        counsel.
      </p>

      <LegalSection title="1. What BikeFair is">
        <p>
          {BRAND_NAME} ("we," "us") operates an online marketplace that facilitates connections between individuals seeking to buy or sell used bicycles locally.
          {BRAND_NAME} is a venue only. We are not a party to any transaction between a buyer and a seller.
        </p>
      </LegalSection>

      <LegalSection title="2. The marketplace facilitates connections; it does not process bicycle sales">
        <p>
          The actual sale of a bicycle — including price negotiation, payment, and physical exchange — occurs directly between the buyer and the seller, offline.
          {BRAND_NAME} does not process, hold, or guarantee any payment for the bicycle itself, does not take title to or ownership of any bicycle listed on the
          platform, and is not responsible for the condition, legality of sale, or ownership history of any bicycle.
        </p>
      </LegalSection>

      <LegalSection title="3. Marketplace fees are separate from the bicycle's price">
        <p>
          {BRAND_NAME} may charge fees for marketplace services — such as featured or premium listing placement, or a seller closing fee on completed transactions. These
          fees are configured in our fee schedule, are charged for use of the platform, and are entirely separate from the price paid for the bicycle itself, which is
          never processed by {BRAND_NAME}.
        </p>
      </LegalSection>

      <LegalSection title="4. Estimated Fair Market Value is an estimate, not a guarantee">
        <p>
          Any "Estimated Fair Market Value" shown on the platform is generated by an automated, rules-based estimation tool based on information provided by the seller
          and general market patterns. It is not an appraisal, is not guaranteed to be accurate, and should not be relied upon as the sole basis for any purchase or sale
          decision.
        </p>
      </LegalSection>

      <LegalSection title="5. Verification levels and badges">
        <p>
          "Verified User" and "Trusted Seller" badges reflect the completion of specific, limited verification steps (such as confirmed email and phone) and/or platform
          activity history (completed transactions, ratings, account age, and absence of unresolved reports). These badges are not a guarantee of a user's identity,
          trustworthiness, or the legality of any bicycle they list, and do not constitute a background check.
        </p>
      </LegalSection>

      <LegalSection title="6. Meetup locations, including participating bike shops">
        <p>
          Meetup locations — including public locations, participating bicycle shops, and any law-enforcement-supported exchange locations referenced on the
          platform — are provided as informational conveniences only. A participating bicycle shop is not a party to any transaction and is not responsible for the
          bicycle, buyer, seller, payment, ownership, condition, or outcome of any transaction, unless that shop has been separately engaged and paid for a distinct
          service, such as a professional inspection. {BRAND_NAME} does not operate, employ, or represent any law enforcement agency.
        </p>
      </LegalSection>

      <LegalSection title="7. User conduct and reporting">
        <p>
          Users agree not to list stolen property, misrepresent a bicycle's condition or ownership, or engage in fraud or harassment. {BRAND_NAME} reviews reports of
          suspected violations and may remove listings, flag serial numbers for internal review, or suspend accounts, but does not adjudicate criminal matters or make
          public accusations based solely on an automated match.
        </p>
      </LegalSection>

      <LegalSection title="8. Disclaimers and limitation of liability">
        <p>
          The platform is provided "as is." {BRAND_NAME} disclaims all warranties regarding the accuracy of listings, valuations, or user-provided information, and
          disclaims liability for the acts or omissions of buyers, sellers, or third-party meetup locations, to the fullest extent permitted by law.
        </p>
      </LegalSection>

      <p className="mt-10 text-xs text-charcoal-400">Last updated: placeholder date. Replace with your organization's actual legal terms before launch.</p>
    </div>
  );
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="font-display text-lg font-bold text-charcoal-900">{title}</h2>
      <div className="mt-2 text-sm leading-relaxed text-charcoal-600">{children}</div>
    </section>
  );
}
